### ISSUE TITLE
Implantation de FRW au MELCCFP

### ISSUE THREAD

**Issue by TommyTEnviroQc** [MTESSDev/azurepipeline-mtess-frw-deploiement#1]
Bonjour!
Je suis chargé de mettre en place le pipeline au MELCCFP et j'ai quelques questions pour procéder.

La première est la disparité entre la procédure et ce que j'ai dans l'extention d'Azure DevOps

Les captures ici: https://marketplace.visualstudio.com/items?itemName=MTESS.mtess-frw-deploiement

Ne concordent pas avec ce qu'on me demande:
![image](https://github.com/user-attachments/assets/15bed7e4-8a8f-4654-b2b3-143a701db219)

J'aimerais savoir aussi ce que je dois entrer comme information (Répertoire, Numéro publique et qui je contact pour obtenir notre cléé API)

Merci beaucoup!

**Comment by anisite** [comment]
Bonjour,

Désolé pour le délai de réponse, premièrement, concernant la différence de l'affichage, c'est probablement du à une différence de version de Azure DevOps, nous avons la version serveur "on prem" de 2019 je crois. 


Le ``display name`` ne servait que pour l'affichage dans le pipeline, les ``...`` manquants je ne peux pas dire.

le répertoire des formulaires est la "source" donc le répertoire dans lequel vous aurez copié le ou les formulaires (certains en copie plusieurs d'autres font un pipeline par formulaire) donc vous allez copier dans le répertoire ``drop`` le répertoire du formulaire à copier, il est important que le répertoire "source" précisé contiennent que le répertoire du formulaire désiré 

Un exemple d'Arborescence : 
````
source
│   default.v0.yml  #(facultatif, s'appliquera à TOUS les formulaires)  
│   transmission.v0.yaml #(facultatif, s'appliquera à TOUS les formulaires)    
│
└───MONFORMULAIRE
│   │   MONFORMULAIRE.v1.form.yml
│   │   MONFORMULAIRE.v1.bind.yml #(facultatif)
|   |   MONFORMULAIRE.v0.transmission.yml #(facultatif)
│   │
│   └───Gabarits #(facultatif)
│       │   formulaire.pdf
│       │   gabarit.docx
│       │   etc ...
````

donc en renseignant le répertoire "source" qu'on voit plus haut dans le champ ``Répertoire des formulaires`` notre extensions va créer un zip avec son contenu et le déployer dans notre système.

Pour les clés api et les guid de numéros publiques c'est @loima02  qui va vous les fournir si ce n'est pas déjà fait, il entrera en contact avec vous, il nous faudra au moins le nom de votre équipe et le numéro du ministère (pour le MESS c'est 700)


Au plaisir, n'hésitez pas s'il y a autre choses !

**Comment by TommyTEnviroQc** [comment]
Merci pour le retour Anisite, notre numéro de ministère est le 0380, soit pour le  Ministère de l’Environnement, de la Lutte contre les changements climatiques, de la Faune et des Parcs.
Notre nom d'équipe est "Solutions légères".

Vous pouvez envoyer les informations sensibles via courriel, à Tommy.Turbide@environnement.gouv.qc.ca

De ce que j'en comprend, il faudra aussi autoriser nos adresses IP (whitelist) de votre coté. Je pourrais vous transmettre le tout via courriel. 

Merci encore!

**Comment by loima02** [comment]
Je regarde ça!
